### ISSUE TITLE
The app won't project results on discord (Solved)

### ISSUE THREAD

**Issue by ArkaynoTCD** [Olian04/dnd-beyond-to-discord#1]
Recently me and my friends were trying to use the app in one of our dnd sessions but when we rolled dices in dnd beyond, it didn't show results in discord channel.

If it can be fixed, please let me know, if not, thanks in advance.

**Comment by Olian04** [comment]
Thank you for bringing this to my attention. I was aware of the issue, but I wasn't sure if it was just local on my machine or not. The extension worked fine a week ago, so dndbeyond must have changed something on their website in the last 7 days that broke the extension. I'm currently looking into it.

**Comment by Olian04** [comment]
~A fixed version (version 1.2.0) has been submitted to google for review, it will be available for installation soon. I will leave this issue open until it's verified that version 1.2.0 fixes this issue.~

As a side note, firefox support has been dropped for the foreseeable future due to limitations with the firefox extension API.

**Comment by Olian04** [comment]
A fixed version (version 1.2.0) is now available. Please update to the latest version :smile:

**Comment by ArkaynoTCD** [comment]
Thank you for fixing and making app that's really nice.
